markdown: rdiscount
permalink: /:title/
url: http://xiye.me
name: 西北西野
author: 西野
qq: 445435642
email: xiyeme@gmail.com
duoshuo: xiye
cnzz: 1253126815
weibo: 2125251795
github: FaTiaoNiao
pygments: true
safe: true
paginate: 20
about: "西安土著，陕西国力（虽然已不存在）、曼联球迷，爱历史与小说，好骑车与徒步旅行，曾经的码农，现在的贫农，无主之地，OVER!"
